# Generated by Django 6.0.1 on 2026-02-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listening", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testresult",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userresponse",
            name="user",
        ),
        migrations.AlterField(
            model_name="testresult",
            name="session_key",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="userresponse",
            name="session_key",
            field=models.CharField(max_length=100),
        ),
    ]
