# Generated by Django 6.0.1 on 2026-02-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listening", "0002_remove_testresult_user_remove_userresponse_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="audioquestion",
            name="alternative_answers",
            field=models.TextField(
                blank=True,
                help_text="JSON list of alternative correct answers (e.g., ['nervousness', 'she was nervous', 'anxiety'])",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userresponse",
            name="matched_keywords",
            field=models.TextField(
                blank=True, help_text="Keywords that matched the answer"
            ),
        ),
        migrations.AlterField(
            model_name="audioquestion",
            name="keywords",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated keywords for auto-grading typing answers",
            ),
        ),
    ]
