# Generated by Django 6.0.1 on 2026-02-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listening", "0003_audioquestion_alternative_answers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userresponse",
            name="matched_keywords",
        ),
        migrations.AddField(
            model_name="userresponse",
            name="matched_answer",
            field=models.TextField(
                blank=True, help_text="Which answer pattern was matched"
            ),
        ),
        migrations.AlterField(
            model_name="audioquestion",
            name="alternative_answers",
            field=models.TextField(
                blank=True,
                help_text="JSON list of alternative correct answer phrases (e.g., ['she was nervous', 'her nervousness', 'anxiety'])",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="audioquestion",
            name="correct_answer_text",
            field=models.TextField(
                blank=True,
                help_text="Primary correct answer for typing questions (exact phrase matching)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="audioquestion",
            name="keywords",
            field=models.TextField(
                blank=True, help_text="DEPRECATED: Use alternative_answers instead"
            ),
        ),
    ]
