# Generated by Django 6.0.1 on 2026-02-16 10:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listening", "0004_alter_answeroption_id_alter_audioquestion_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testresult",
            name="completed_at",
        ),
        migrations.AddField(
            model_name="testresult",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="testresult",
            name="percentage",
            field=models.FloatField(default=0),
        ),
    ]
