# Generated by Django 5.2.11 on 2026-02-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listening', '0006_alter_answeroption_id_alter_audioquestion_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audioquestion',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='testresult',
            old_name='created_at',
            new_name='completed_at',
        ),
        migrations.AlterField(
            model_name='audioquestion',
            name='transcript',
            field=models.TextField(blank=True, help_text="Full text of what's spoken in audio"),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
