# Generated by Django 6.0.1 on 2026-02-26 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WritingTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="WritingQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=1)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("fill_blanks", "Fill in the Blanks"),
                            ("sentence_order", "Sentence Arrangement"),
                            ("sentence_rewrite", "Sentence Rewriting"),
                            ("spelling_mcq", "Spelling Multiple Choice"),
                            ("paragraph_writing", "Paragraph Writing"),
                        ],
                        max_length=50,
                    ),
                ),
                ("prompt", models.TextField()),
                (
                    "correct_answer",
                    models.TextField(help_text="Main correct answer for auto-checking"),
                ),
                (
                    "acceptable_answers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of other acceptable answers in JSON format",
                    ),
                ),
                ("explanation", models.TextField(blank=True)),
                (
                    "picture_filename",
                    models.CharField(
                        blank=True,
                        help_text="Name of image file in static folder",
                        max_length=200,
                    ),
                ),
                (
                    "required_keywords",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Keywords that should be present",
                    ),
                ),
                ("min_sentences", models.IntegerField(default=2)),
                ("min_words", models.IntegerField(default=15)),
                ("max_words", models.IntegerField(default=50)),
                (
                    "audio_filename",
                    models.CharField(
                        blank=True,
                        help_text="Name of audio file for dictation",
                        max_length=200,
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="writing.writingtest",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("test", "order")},
            },
        ),
        migrations.CreateModel(
            name="WritingTestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=100)),
                ("total_score", models.FloatField(default=0)),
                ("max_score", models.IntegerField(default=5)),
                ("percentage", models.FloatField(default=0)),
                ("level", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="writing.writingtest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WritingResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=100)),
                ("user_answer", models.TextField()),
                ("score", models.FloatField(default=0, help_text="Score out of 100")),
                (
                    "feedback",
                    models.JSONField(
                        blank=True, default=list, help_text="List of feedback points"
                    ),
                ),
                ("needs_manual_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="writing.writingquestion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("session_key", "question")},
            },
        ),
    ]
