# Generated by Django 6.0.1 on 2026-02-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writing", "0003_alter_writingquestion_id_alter_writingresponse_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="writingquestion",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="writingresponse",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="writingtest",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="writingtestresult",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
