# Generated by Django 6.0.1 on 2026-02-16 10:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writing", "0004_alter_writingquestion_id_alter_writingresponse_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="writingtestresult",
            name="completed_at",
        ),
        migrations.AddField(
            model_name="writingtestresult",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="writingtestresult",
            name="percentage",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="writingtestresult",
            name="total_score",
            field=models.FloatField(default=0),
        ),
    ]
