# Generated by Django 5.2.11 on 2026-02-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0005_remove_writingtestresult_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingquestion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='writingresponse',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='writingtest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='writingtestresult',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
