# Generated by Django 5.2.11 on 2026-02-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0006_alter_writingquestion_id_alter_writingresponse_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingtestresult',
            name='level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
