# Generated by Django 6.0.2 on 2026-02-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0008_alter_writingquestion_id_alter_writingresponse_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='writingquestion',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='writingquestion',
            name='question_type',
            field=models.CharField(choices=[('fill_blanks', 'Fill in the Blanks'), ('sentence_order', 'Sentence Arrangement'), ('sentence_rewrite', 'Sentence Rewriting'), ('spelling_mcq', 'Spelling Multiple Choice'), ('paragraph_writing', 'Paragraph Writing')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='writingquestion',
            unique_together={('test', 'order')},
        ),
    ]
