# Generated by Django 6.0.2 on 2026-02-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0009_alter_writingquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingresponse',
            name='score',
            field=models.FloatField(default=0, help_text='Score out of 100'),
        ),
    ]
