# Generated by Django 5.2.11 on 2026-02-21 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='paragraph',
        ),
        migrations.AddField(
            model_name='question',
            name='parameter_type',
            field=models.CharField(choices=[('MAIN_IDEA', 'Comprehension of Main Idea'), ('VOCAB', 'Lexical Interpretation Skill'), ('DETAIL', 'Understanding of Specific Details'), ('LOGICAL', 'Understanding of Organisation & Logical Thoughts')], default='MAIN_IDEA', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='weight',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='readinguserresponse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('content', models.TextField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='reading.test')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='paragraph',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='reading.paragraph'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ReadingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('level', models.CharField(default='Basic', max_length=20)),
                ('feedback', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reading.test')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
