# Generated by Django 6.0.1 on 2026-02-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_alter_question_id_alter_test_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='paragraph',
            field=models.TextField(default="Global warming is one of the most serious challenges facing the world today. It occurs when greenhouse gases like carbon dioxide trap heat in the Earth's atmosphere, causing temperatures to rise. This leads to melting ice caps, rising sea levels, and extreme weather events. Humans contribute to global warming through activities such as burning fossil fuels, deforestation, and industrial processes. To reduce its impact, people can adopt cleaner energy sources, plant more trees, and reduce waste. Understanding the causes and effects of global warming is essential for protecting our planet for future generations. Everyone has a role to play in creating a sustainable and healthy environment."),
        ),
    ]
