# Generated by Django 5.2.11 on 2026-02-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_remove_test_paragraph_question_parameter_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingresult',
            name='lexical_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='readingresult',
            name='main_idea_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='readingresult',
            name='organisation_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='readingresult',
            name='specific_score',
            field=models.IntegerField(default=0),
        ),
    ]
