# Generated by Django 5.2.11 on 2026-02-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_alter_question_id_alter_test_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
