# Generated by Django 6.0.1 on 2026-02-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reading", "0003_test_paragraph"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="paragraph",
            field=models.TextField(
                default="Engineering life is not only about studying machines, drawings, or technical subjects. It is also about developing important skills that help students become successful professionals. Diploma engineering students learn how to solve problems, work in teams, and manage time effectively during their academic life. One of the most important skills for an engineering student is problem-solving. Engineers often face real-life challenges where they must think logically and find practical solutions. Along with this, communication skills play a key role. Engineers need to explain their ideas clearly to supervisors, co-workers, and clients. Good communication helps avoid mistakes and improves teamwork. Time management is another essential skill in engineering life. Students have to balance classes, practical work, assignments, and exams. Managing time properly reduces stress and improves performance. Teamwork is equally important because most engineering projects are completed in groups. Working with others teaches cooperation, responsibility, and respect for different opinions. Finally, engineering life also teaches discipline and professionalism. Following rules, maintaining safety, and being punctual are habits that prepare students for industry life. These skills not only help students during their studies but also make them confident and successful engineers in the future."
            ),
        ),
    ]
