# Generated by Django 5.2.11 on 2026-02-13 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0003_alter_question_id_alter_test_id'),
        ('reading', '0004_alter_test_paragraph'),
    ]

    operations = [
    ]
