# Generated by Django 6.0.1 on 2026-03-05 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reading", "0004_suspiciousactivity"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SuspiciousActivity",
        ),
    ]
