# Generated by Django 6.0.1 on 2026-03-29 10:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prerequisite",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="learning.level",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_number",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ]
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("power_line", models.CharField(blank=True, max_length=500)),
                (
                    "estimated_time",
                    models.IntegerField(default=30, help_text="Minutes"),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="learning.level",
                    ),
                ),
            ],
            options={
                "ordering": ["day_number"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("listening", "Listening"),
                            ("reading", "Reading"),
                            ("writing", "Writing"),
                            ("speaking", "Speaking"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField()),
                ("instructions", models.TextField(blank=True)),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="learning.day",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("mcq", "Multiple Choice Question"),
                            ("text", "Text Answer"),
                            ("audio", "Audio/Listening Task"),
                            ("speaking", "Speaking Task"),
                        ],
                        max_length=20,
                    ),
                ),
                ("question", models.TextField()),
                ("instructions", models.TextField(blank=True)),
                ("order", models.IntegerField()),
                ("audio_url", models.URLField(blank=True, help_text="For audio tasks")),
                (
                    "image_url",
                    models.URLField(blank=True, help_text="For tasks with images"),
                ),
                (
                    "word_limit",
                    models.IntegerField(
                        blank=True, help_text="For writing tasks", null=True
                    ),
                ),
                (
                    "correct_answer",
                    models.TextField(
                        blank=True,
                        help_text="For text tasks, store expected answer for auto-evaluation",
                    ),
                ),
                (
                    "expected_keywords",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Keywords to check in speaking responses",
                    ),
                ),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                ("points", models.IntegerField(default=10)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="learning.section",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                ("is_correct", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=1)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="learning.task",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="UserDayProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("listening_completed", models.BooleanField(default=False)),
                ("reading_completed", models.BooleanField(default=False)),
                ("writing_completed", models.BooleanField(default=False)),
                ("speaking_completed", models.BooleanField(default=False)),
                ("user_answers", models.JSONField(blank=True, default=dict)),
                ("score", models.FloatField(default=0)),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="learning.day"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="day_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserLevelUnlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_unlocked", models.BooleanField(default=False)),
                ("unlocked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="learning.level"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unlocked_levels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserTaskAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.TextField(blank=True)),
                ("is_correct", models.BooleanField(default=False)),
                ("score_earned", models.FloatField(default=0)),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "day_progress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_answers",
                        to="learning.userdayprogress",
                    ),
                ),
                (
                    "selected_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="learning.option",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="learning.task"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="level",
            index=models.Index(fields=["name"], name="learning_le_name_a988eb_idx"),
        ),
        migrations.AddIndex(
            model_name="level",
            index=models.Index(fields=["order"], name="learning_le_order_abfdb2_idx"),
        ),
        migrations.AddIndex(
            model_name="day",
            index=models.Index(
                fields=["level", "day_number"], name="learning_da_level_i_0df1a9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="day",
            unique_together={("level", "day_number")},
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["day", "order"], name="learning_se_day_id_1debc6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("day", "name")},
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["section", "order"], name="learning_ta_section_ce4d4c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["task_type"], name="learning_ta_task_ty_ef6909_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="option",
            index=models.Index(fields=["task"], name="learning_op_task_id_d0502a_idx"),
        ),
        migrations.AddIndex(
            model_name="userdayprogress",
            index=models.Index(
                fields=["user", "day"], name="learning_us_user_id_68e43d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userdayprogress",
            index=models.Index(
                fields=["is_completed"], name="learning_us_is_comp_9a5eb4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userdayprogress",
            unique_together={("user", "day")},
        ),
        migrations.AddIndex(
            model_name="userlevelunlock",
            index=models.Index(
                fields=["user", "level"], name="learning_us_user_id_5a86cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userlevelunlock",
            index=models.Index(
                fields=["is_unlocked"], name="learning_us_is_unlo_d9b153_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userlevelunlock",
            unique_together={("user", "level")},
        ),
        migrations.AddIndex(
            model_name="usertaskanswer",
            index=models.Index(
                fields=["user", "task"], name="learning_us_user_id_972e17_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usertaskanswer",
            index=models.Index(
                fields=["day_progress"], name="learning_us_day_pro_48e356_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usertaskanswer",
            unique_together={("user", "task")},
        ),
    ]
