# Generated by Django 6.0.1 on 2026-03-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdayprogress",
            name="activity_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="section",
            name="name",
            field=models.CharField(
                choices=[
                    ("listening", "Listening"),
                    ("reading", "Reading"),
                    ("writing", "Writing"),
                    ("speaking", "Speaking"),
                    ("game", "Activity"),
                    ("activity", "Activity"),
                ],
                max_length=20,
            ),
        ),
    ]
