# Generated by Django 6.0.1 on 2026-03-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_type', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('day', models.IntegerField()),
                ('sentence', models.TextField()),
                ('meaning', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/listening/')),
                ('test_question', models.TextField()),
                ('test_option_a', models.CharField(max_length=500)),
                ('test_option_b', models.CharField(max_length=500)),
                ('test_option_c', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_type', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('day', models.IntegerField()),
                ('paragraph', models.TextField()),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/reading/')),
                ('vocabulary', models.TextField(help_text='Word:Meaning,Word:Meaning format')),
                ('explanation', models.TextField()),
                ('test_question', models.TextField()),
                ('test_option_a', models.CharField(max_length=500)),
                ('test_option_b', models.CharField(max_length=500)),
                ('test_option_c', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_type', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('day', models.IntegerField()),
                ('sentence', models.TextField()),
                ('slow_audio', models.FileField(blank=True, null=True, upload_to='audio/speaking/slow/')),
                ('normal_audio', models.FileField(blank=True, null=True, upload_to='audio/speaking/normal/')),
                ('sentence_parts', models.TextField(help_text='Comma-separated parts of the sentence')),
                ('test_task', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WritingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_type', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('day', models.IntegerField()),
                ('structure', models.TextField()),
                ('suggestions', models.TextField(help_text='Comma-separated suggestions')),
                ('example', models.TextField()),
                ('test_task', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_type', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('day', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('learning_objectives', models.TextField(blank=True)),
                ('key_points', models.TextField(blank=True)),
                ('examples', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['level_type', 'day'],
                'unique_together': {('level_type', 'day')},
            },
        ),
    ]
