# Generated by Django 6.0.1 on 2026-03-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0002_userdayprogress_activity_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="day",
            name="completion_checklist",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="day",
            name="grammar_examples",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="day",
            name="grammar_rule",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="day",
            name="idiom",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="day",
            name="idiom_meaning",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="day",
            name="vocabulary",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="section",
            name="name",
            field=models.CharField(
                choices=[
                    ("listening", "Listening"),
                    ("reading", "Reading"),
                    ("writing", "Writing"),
                    ("speaking", "Speaking"),
                    ("activity", "Activity"),
                ],
                max_length=20,
            ),
        ),
    ]
