# Generated by Django 6.0.1 on 2026-03-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0003_day_completion_checklist_day_grammar_examples_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="custom_title",
            field=models.CharField(
                blank=True,
                help_text="Custom title for this section (overrides default name)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="emoji",
            field=models.CharField(
                blank=True,
                default="📚",
                help_text="Emoji for section (e.g., 🎧, 🗣️, 📖, ✍️, 🎲)",
                max_length=10,
            ),
        ),
    ]
