# Generated by Django 6.0.1 on 2026-03-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0004_section_custom_title_section_emoji"),
    ]

    operations = [
        migrations.RenameField(
            model_name="section",
            old_name="emoji",
            new_name="icon",
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("day", "order")},
        ),
        migrations.RemoveField(
            model_name="userdayprogress",
            name="activity_completed",
        ),
        migrations.RemoveField(
            model_name="userdayprogress",
            name="listening_completed",
        ),
        migrations.RemoveField(
            model_name="userdayprogress",
            name="reading_completed",
        ),
        migrations.RemoveField(
            model_name="userdayprogress",
            name="speaking_completed",
        ),
        migrations.RemoveField(
            model_name="userdayprogress",
            name="writing_completed",
        ),
        migrations.AddField(
            model_name="day",
            name="subtitle",
            field=models.CharField(
                blank=True,
                help_text="Optional subtitle for hero section",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="title",
            field=models.CharField(
                blank=True, help_text="Override default section name", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="title",
            field=models.CharField(
                blank=True, help_text="Optional task title", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="userdayprogress",
            name="completed_sections",
            field=models.JSONField(
                blank=True, default=dict, help_text="{'section_name': True/False}"
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="vocabulary",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of vocabulary words with meaning, synonym, antonym",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="order",
            field=models.IntegerField(help_text="Display order (1, 2, 3, 4, 5)"),
        ),
        migrations.AlterField(
            model_name="task",
            name="correct_answer",
            field=models.TextField(
                blank=True, help_text="For text tasks, store expected answer"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="expected_keywords",
            field=models.JSONField(
                blank=True, default=list, help_text="Keywords to check in responses"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="extra_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Flexible data storage"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="instructions",
            field=models.TextField(blank=True, help_text="Additional instructions"),
        ),
        migrations.AlterField(
            model_name="task",
            name="order",
            field=models.IntegerField(help_text="Display order within section"),
        ),
        migrations.AlterField(
            model_name="task",
            name="question",
            field=models.TextField(help_text="Main question or prompt"),
        ),
        migrations.RemoveField(
            model_name="section",
            name="custom_title",
        ),
    ]
