# Generated by Django 6.0.1 on 2026-04-02 06:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0005_rename_emoji_section_icon_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(max_length=20)),
                (
                    "day_number",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ]
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("listening", "Listening"),
                            ("speaking", "Speaking"),
                            ("reading", "Reading"),
                            ("writing", "Writing"),
                            ("vocabulary", "Vocabulary"),
                            ("grammar", "Grammar"),
                            ("game", "Game"),
                        ],
                        max_length=20,
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("recording_url", models.URLField(blank=True, null=True)),
                ("response_data", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ["day_number", "activity_type"],
            },
        ),
        migrations.CreateModel(
            name="SavedVocabulary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=100)),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-saved_at"],
            },
        ),
        migrations.CreateModel(
            name="UserCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=20,
                    ),
                ),
                ("certificate_code", models.CharField(max_length=100, unique=True)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("downloaded", models.BooleanField(default=False)),
                ("shared", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="UserLearningProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=20,
                    ),
                ),
                ("completed_days", models.JSONField(default=list)),
                (
                    "current_day",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ],
                    ),
                ),
                ("streak_days", models.IntegerField(default=0)),
                ("last_completed_date", models.DateField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("certificate_issued", models.BooleanField(default=False)),
                ("certificate_issued_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="day",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="day",
            name="learning_da_level_i_0df1a9_idx",
        ),
        migrations.RemoveIndex(
            model_name="level",
            name="learning_le_name_a988eb_idx",
        ),
        migrations.RemoveIndex(
            model_name="level",
            name="learning_le_order_abfdb2_idx",
        ),
        migrations.RemoveIndex(
            model_name="option",
            name="learning_op_task_id_d0502a_idx",
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="section",
            name="learning_se_day_id_1debc6_idx",
        ),
        migrations.RemoveIndex(
            model_name="task",
            name="learning_ta_section_ce4d4c_idx",
        ),
        migrations.RemoveIndex(
            model_name="task",
            name="learning_ta_task_ty_ef6909_idx",
        ),
        migrations.AlterUniqueTogether(
            name="userdayprogress",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="userdayprogress",
            name="learning_us_user_id_68e43d_idx",
        ),
        migrations.RemoveIndex(
            model_name="userdayprogress",
            name="learning_us_is_comp_9a5eb4_idx",
        ),
        migrations.AlterUniqueTogether(
            name="userlevelunlock",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="userlevelunlock",
            name="learning_us_user_id_5a86cc_idx",
        ),
        migrations.RemoveIndex(
            model_name="userlevelunlock",
            name="learning_us_is_unlo_d9b153_idx",
        ),
        migrations.AlterUniqueTogether(
            name="usertaskanswer",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="usertaskanswer",
            name="learning_us_user_id_972e17_idx",
        ),
        migrations.RemoveIndex(
            model_name="usertaskanswer",
            name="learning_us_day_pro_48e356_idx",
        ),
        migrations.AddField(
            model_name="dailyactivity",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="savedvocabulary",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_vocabulary",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usercertificate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userlearningprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="learning_progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="day",
            name="level",
        ),
        migrations.RemoveField(
            model_name="level",
            name="prerequisite",
        ),
        migrations.RemoveField(
            model_name="option",
            name="task",
        ),
        migrations.RemoveField(
            model_name="task",
            name="section",
        ),
        migrations.RemoveField(
            model_name="userdayprogress",
            name="day",
        ),
        migrations.RemoveField(
            model_name="userdayprogress",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userlevelunlock",
            name="level",
        ),
        migrations.RemoveField(
            model_name="userlevelunlock",
            name="user",
        ),
        migrations.RemoveField(
            model_name="usertaskanswer",
            name="day_progress",
        ),
        migrations.RemoveField(
            model_name="usertaskanswer",
            name="selected_option",
        ),
        migrations.RemoveField(
            model_name="usertaskanswer",
            name="task",
        ),
        migrations.RemoveField(
            model_name="usertaskanswer",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="dailyactivity",
            unique_together={("user", "level", "day_number", "activity_type")},
        ),
        migrations.AlterUniqueTogether(
            name="savedvocabulary",
            unique_together={("user", "word")},
        ),
        migrations.AlterUniqueTogether(
            name="usercertificate",
            unique_together={("user", "level")},
        ),
        migrations.AlterUniqueTogether(
            name="userlearningprogress",
            unique_together={("user", "level")},
        ),
        migrations.DeleteModel(
            name="Section",
        ),
        migrations.DeleteModel(
            name="Day",
        ),
        migrations.DeleteModel(
            name="Level",
        ),
        migrations.DeleteModel(
            name="UserLevelUnlock",
        ),
        migrations.DeleteModel(
            name="UserDayProgress",
        ),
        migrations.DeleteModel(
            name="Option",
        ),
        migrations.DeleteModel(
            name="Task",
        ),
        migrations.DeleteModel(
            name="UserTaskAnswer",
        ),
    ]
