# Generated by Django 6.0.1 on 2026-04-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0006_dailyactivity_savedvocabulary_usercertificate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercertificate",
            name="certificate_image",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usercertificate",
            name="download_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usercertificate",
            name="share_count",
            field=models.IntegerField(default=0),
        ),
    ]
