# Generated by Django 6.0.1 on 2026-04-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0007_usercertificate_certificate_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlearningprogress",
            name="has_seen_intro",
            field=models.BooleanField(default=False),
        ),
    ]
