# Generated by Django 6.0.1 on 2026-04-10 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0008_userlearningprogress_has_seen_intro"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LevelAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(default="Final Assessment", max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Instructions for the assessment"
                    ),
                ),
                (
                    "passing_score",
                    models.IntegerField(default=15, help_text="Minimum score to pass"),
                ),
                (
                    "time_limit_minutes",
                    models.IntegerField(default=30, help_text="Time limit in minutes"),
                ),
                (
                    "total_questions",
                    models.IntegerField(default=20, help_text="Number of questions"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Level Assessment",
                "verbose_name_plural": "Level Assessments",
                "ordering": ["level"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(help_text="Question text")),
                ("option_a", models.CharField(help_text="Option A", max_length=500)),
                ("option_b", models.CharField(help_text="Option B", max_length=500)),
                (
                    "option_c",
                    models.CharField(
                        blank=True, help_text="Option C (optional)", max_length=500
                    ),
                ),
                (
                    "option_d",
                    models.CharField(
                        blank=True, help_text="Option D (optional)", max_length=500
                    ),
                ),
                (
                    "correct_answer",
                    models.CharField(
                        choices=[("a", "A"), ("b", "B"), ("c", "C"), ("d", "D")],
                        help_text="Correct answer letter",
                        max_length=1,
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True, help_text="Explanation of the correct answer"
                    ),
                ),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="learning.levelassessment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assessment Question",
                "verbose_name_plural": "Assessment Questions",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="UserAssessmentAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=20,
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("total_questions", models.IntegerField(default=0)),
                ("percentage", models.FloatField(default=0)),
                ("passed", models.BooleanField(default=False)),
                (
                    "answers",
                    models.JSONField(default=dict, help_text="Stores user's answers"),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("time_taken_seconds", models.IntegerField(default=0)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="learning.levelassessment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Assessment Attempt",
                "verbose_name_plural": "User Assessment Attempts",
                "ordering": ["-completed_at"],
            },
        ),
    ]
