# Generated by Django 6.0.1 on 2026-04-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0009_levelassessment_assessmentquestion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlearningprogress",
            name="collected_rewards",
            field=models.JSONField(default=list),
        ),
    ]
