# Generated by Django 5.2.11 on 2026-02-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(default='Student', max_length=100)),
                ('audio_file', models.FileField(upload_to='speaking/recordings/')),
                ('text_to_read', models.TextField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('mispronounced_words', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
