# Generated by Django 5.2.11 on 2026-02-25 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('roll_number', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('q1_word1_recording', models.CharField(blank=True, max_length=500)),
                ('q1_word2_recording', models.CharField(blank=True, max_length=500)),
                ('q1_word3_recording', models.CharField(blank=True, max_length=500)),
                ('q1_word4_recording', models.CharField(blank=True, max_length=500)),
                ('q1_word5_recording', models.CharField(blank=True, max_length=500)),
                ('q1_word1_score', models.FloatField(default=0)),
                ('q1_word2_score', models.FloatField(default=0)),
                ('q1_word3_score', models.FloatField(default=0)),
                ('q1_word4_score', models.FloatField(default=0)),
                ('q1_word5_score', models.FloatField(default=0)),
                ('q1_score', models.FloatField(default=0)),
                ('q2_score', models.FloatField(default=0)),
                ('q3_score', models.FloatField(default=0)),
                ('q4_score', models.FloatField(default=0)),
                ('q5_score', models.FloatField(default=0)),
                ('q2_recording', models.CharField(blank=True, max_length=500)),
                ('q3_recording', models.CharField(blank=True, max_length=500)),
                ('q4_recording', models.CharField(blank=True, max_length=500)),
                ('q5_recording', models.CharField(blank=True, max_length=500)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to='speaking.student')),
            ],
        ),
        migrations.DeleteModel(
            name='QuestionResponse',
        ),
        migrations.DeleteModel(
            name='SpeakingSession',
        ),
    ]
