# Generated by Django 5.2.11 on 2026-02-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking', '0002_alter_recording_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
