# Generated by Django 6.0.1 on 2026-03-11 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speaking", "0002_testsession_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SuspiciousActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("tab_switch", "Tab Switch"),
                            ("fullscreen_exit", "Fullscreen Exit"),
                            ("window_blur", "Window Blur"),
                            ("too_fast", "Answered Too Fast"),
                            ("away_from_keyboard", "Away from Keyboard"),
                            ("right_click", "Right Click Attempt"),
                            ("copy_attempt", "Copy Attempt"),
                            ("dev_tools", "Developer Tools Attempt"),
                        ],
                        max_length=50,
                    ),
                ),
                ("count", models.IntegerField(default=1)),
                ("question", models.IntegerField(default=1)),
                ("test_type", models.CharField(default="speaking", max_length=20)),
                ("time_away", models.IntegerField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speaking_suspicious_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Speaking Suspicious Activities",
                "ordering": ["-timestamp"],
            },
        ),
    ]
