# Generated by Django 6.0.1 on 2026-02-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speaking", "0003_alter_recording_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recording",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
