# Generated by Django 5.2.11 on 2026-02-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking', '0006_alter_recording_id_alter_speakingresult_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingresult',
            name='level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
