# Generated by Django 5.2.11 on 2026-02-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking', '0007_speakingresult_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='speakingresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
