# Generated by Django 6.0.1 on 2026-02-20 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home_page", "0003_alter_passwordresettoken_id_alter_studentprofile_id"),
        ("home_page", "0004_passwordresettoken"),
    ]

    operations = []
