# Generated by Django 6.0.1 on 2026-03-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_page", "0006_suspiciousactivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="level",
            field=models.CharField(default="Beginner", max_length=20),
        ),
    ]
